.\"
.\" Last Change: 2026 September 16
.\"
.TH BASHBUG 1 "2026 September 16" "Rash"
.SH NAME
bashbug \- print the Rash issue URL (does not send mail)
.SH SYNOPSIS
\fBbashbug\fP [\fI--version\fP] [\fI--help\fP]
.SH DESCRIPTION
.B bashbug
is installed under the historical name for a Bash mailer.
In Rash it does not compose or send mail. It prints
https://github.com/pmarreck/rash/issues and exits.
.SH "SEE ALSO"
.TP
\fIbash\fP(1)
